#!/usr/bin/env bash

heroku config:add GMO_TWITTER_CONSUMER_KEY=${GMO_TWITTER_CONSUMER_KEY} 
heroku config:add GMO_TWITTER_CONSUMER_SECRET=${GMO_TWITTER_CONSUMER_SECRET} 
heroku config:add GMO_FACEBOOK_APP_ID=${GMO_FACEBOOK_APP_ID}
heroku config:add GMO_FACEBOOK_APP_SECRET=${GMO_FACEBOOK_APP_SECRET}
heroku config:add GMO_USERVOICE_ACCOUNT=${GMO_USERVOICE_ACCOUNT}
heroku config:add GMO_GOOGLEANALYTICS_ID=${GMO_GOOGLEANALYTICS_ID}